### ISSUE TITLE
Problems with model training

### ISSUE THREAD

**Issue by gaworj** [chg60/DEPhT#38]
Hi,

Thank you very much for such great tool!

I have successfully installed DEPht using conda. but wanted to train my specific model for Streptococcus phages.

When I try to run: depht_train create_model Streptococcus_depht_model Streptococcus_phages_gbk/ S_pygogenes_fasta/ -f

such error appears:

Process Process-32:
Traceback (most recent call last):
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/functions/multiprocess.py", line 57, in worker
    output_queue.put(func(*args))
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 386, in clean_sequence
    SeqIO.write(records, gb_file, "gb")
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 524, in write
    count = writer_class(handle).write_file(sequences)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 234, in write_file
    count = self.write_records(records, maxcount)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 208, in write_records
    self.write_record(record)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 994, in write_record
    self._write_the_first_line(record)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 749, in _write_the_first_line
    raise ValueError("missing molecule_type in annotations")
ValueError: missing molecule_type in annotations
Process Process-2:
Traceback (most recent call last):
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/functions/multiprocess.py", line 57, in worker
    output_queue.put(func(*args))
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 386, in clean_sequence
    SeqIO.write(records, gb_file, "gb")
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 524, in write
    count = writer_class(handle).write_file(sequences)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 234, in write_file
    count = self.write_records(records, maxcount)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 208, in write_records
    self.write_record(record)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 994, in write_record
    self._write_the_first_line(record)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/Bio/SeqIO/InsdcIO.py", line 749, in _write_the_first_line
    raise ValueError("missing molecule_type in annotations")
ValueError: missing molecule_type in annotations

My annotations were downloaded from NCBI using ncbi-download toolkit. Fasta files for bacterial genomes were decompressed. Gbff genbank files were also decompressed.

Any hints?

Bests,
Jan

**Comment by chg60** [comment]
Hi Jan,

Thank you for your interest in using DEPhT.

We've done a little digging, and suspect that this error was encountered on a flat files with slightly different headers than Biopython was expecting. We updated the code to try and account for these cases and have released a new version of DEPhT that includes these updates.

Would you kindly update your local copy of DEPhT to version 1.1.5 (pip install --upgrade depht) and let me know whether that fixed this problem?  If it does not fix the issue, it would be helpful to have access to a .zip or other compressed archive containing the flat files you are attempting to train on.

Best,

Christian

**Comment by gaworj** [comment]
Hi,

Thank you for your helpfullness.

I have sucessfully updated depht in my conda env using pip as you sugessted.

Unfortunately another problem appeared:

depht_train create_model -c 64 Streptococcus_depht_model_v2 Streptococcus_phages_gbk/ S_pygogenes_fasta/
Traceback (most recent call last):
  File "/home/oligo/anaconda3/envs/depht/bin/depht_train", line 8, in <module>
    sys.exit(main())
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/run.py", line 59, in main
    create_model.main(unparsed_args[1:])
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 508, in main
    create_model(args.name, args.phages, args.bacteria,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 135, in create_model
    bacterial_data_tuple = collect_sequences(
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 301, in collect_sequences
    execute_phamerate_pipeline(fasta_file, gene_clusters_dir,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/phamerate.py", line 182, in execute_phamerate_pipeline
    phams = phamerate(mmseqsdb, input_db, tempdir, first_iter,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/phamerate.py", line 111, in phamerate
    first_iter_phams = mmseqs.parse_mmseqs(first_iter_out)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/functions/mmseqs.py", line 538, in parse_mmseqs
    with filepath.open("r") as fh:
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/oligo/.depht/models/Streptococcus_depht_model_v2/tmp/bacteria/phams/temp/first_iter_out.txt'

Currently I'm not using flat files.   As mentioned before I have used two input folders for model creation: direcotry with fna files for S.pygoenes complete genomes from Genbank and second folder with gbff files containing Streptococcus viruses annotations.

Bests,
Jan

**Comment by chg60** [comment]
Hi Jan,

We've been looking into this, and are a bit confused. It seems as though this issue should only be caused if the input files are empty or non-compliant with the FASTA/GBFF specifications. Would you mind sharing a subset of your .gbff and .fna files so we can try to reproduce this on our end?

Thanks in advance, and sorry that this has taken some time!

Best,

Christian

**Comment by laa89** [comment]
Hi Jan,

We have updated DEPhT to have more robust error handling with unsupported file types.  It should be more informative as to the errors that are occurring, and should exit cleanly without throwing an error.  Please update your DEPhT version to 1.1.6 (with pip install --upgrade depht)

Thank you for your continued cooperation!

**Comment by gaworj** [comment]
Hi,

DEPhT was sucessfully installed. After that I was able to create my model!

Here are some of the last lines of terminal output:

tps: 155        fns: 3  tns: 83357      fps: 7058
(0.9, 0.1): 0.1396366151620745
tps: 155        fns: 3  tns: 83347      fps: 7068
(0.95, 0.05): 0.13953190089983258
tps: 155        fns: 3  tns: 83003      fps: 7412
(1.0, 0.0): 0.13605360537484676
The best weights ((0.5, 0.5)) get average MCC = 0.17017


Pipeline completed.
Time elapsed 409.80s

But when I run phage detection pipeline:

depht -c 64 --model Streptococcus_model_14092022 assemblies/*.fna M28_depht_out
Traceback (most recent call last):
  File "/home/oligo/anaconda3/envs/depht/bin/depht", line 8, in <module>
    sys.exit(main())
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/__main__.py", line 257, in main
    bacterial_masks = assemble_bacterial_mask(
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/functions/mmseqs.py", line 49, in assemble_bacterial_mask
    bacterial_gene_bit_values, clades = parse_gene_bit_value_file(
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht/functions/mmseqs.py", line 577, in parse_gene_bit_value_file
    filehandle = open(filepath, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/oligo/.depht/models/Streptococcus_model_14092022/mmseqs/bacterial_genes.pbv'

It looks like something is still wrong with model creation. 

I have also tried to create the model using such tiny dataset:

a) bacterial acc. numbers:
NC_007296.2
NZ_LS483386.1

b) phage dataset:
AY657002
FM864213

Please let me know how to solve this problem!

Bests,
Jan

**Comment by gaworj** [comment]
Hi,

Depht was upgraded to the newest version.

I've been trying to train my simple model using tiny dataset:

a) bacterial acc. numbers:
NC_007296.2
NZ_LS483386.1

b) phage dataset:
AY657002
FM864213

Here is the terminal output:

depht_train create_model -c 64 Streptococcus_depht_model_v1 phage_gbk S_pyo_genomes/                     Traceback (most recent call last):
  File "/home/oligo/anaconda3/envs/depht/bin/depht_train", line 8, in <module>
    sys.exit(main())
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/run.py", line 59, in main
    create_model.main(unparsed_args[1:])
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 553, in main
    create_model(args.name, args.phages, args.bacteria,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 135, in create_model
    bacterial_data_tuple = collect_sequences(
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 334, in collect_sequences
    cluster_file, cluster_map = create_cluster_schema(
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/depht_train/pipelines/create_model.py", line 523, in create_cluster_schema
    clusters = get_clusters(genome_pham_tsv_file,
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/phamclust/__main__.py", line 110, in get_clusters
    matrix = matrix_de_novo(genomes, func, cpus)
  File "/home/oligo/anaconda3/envs/depht/lib/python3.9/site-packages/phamclust/SymMatrix.py", line 267, in matrix_de_novo
    while len(genomes) / num_batches > batch_size or num_batches % cpus != 0:
ZeroDivisionError: division by zero

Another pipline test with Pseudomonas PAO1 (NC_002516.2) to check whether depht detection pipeline works:

depht PAO1_NCBI_genome.fas PAO1_NCBI_depht -c 64 -m fast --model Pseudomonas

Total runtime: 0:01:03.947185

This time everything was fine. Output files were created successfully.


Bests,
Jan

**Comment by laa89** [comment]
Hi Jan,

Yes sorry, I forgot to mention we upgraded one of our dependancy packages.

Please try again after upgrading your version of phamclust (pip install - - upgrade phamclust)

Best,
Owen

**Comment by gaworj** [comment]
Hi Owen,

Success!

depht assemblies/test_assembly.fna test_normal_depht -c 64 -m normal --model Streptococcus_depht_model_v1
test_normal_depht' does not exist - creating it...

WARNING: no essential phage protein database found in 'Streptococcus_depht_model_v1'
        skipping essential phage gene homolog search.


Total runtime: 0:00:52.851608

Results files were created!

It would be really great if depht tool could generate some summary files for easy parsing in tabular format. Are there any plans? I mean txt file with contig number with prophage, phage coordinates, phage size etc.
Such file will allow easy downstream summarizing of depht results when run on multiple genomes.

Bests,
Jan

**Comment by laa89** [comment]
Hi Jan,

Try upgrading DEPhT to version 1.1.8 (pip install --upgrade depht)

We put in an update that allows you to specify --write_metadata at the command line.  DEPhT will output a csv table to a file called 'metadata.csv' that contains information about the prophages discovered.  Specifically, each row in the csv table corresponds to one prophage and contains information about prophage metadata such as what contig each prophage can be found in as well as their start and end coordinate relative to the sequence of that contig.

Thanks,
Owen
